### ISSUE TITLE
v0.3.2 causes device failure

### ISSUE THREAD

**Issue by rcoletti116** [milo526/homebridge-tuya-web#14]
After latest update 0.3.2 my devices no longer work. I'll roll back for now.

[6/18/2020, 6:29:39 PM] [TuyaWebPlatform] [SET][Outdoor Dimmer Plug] Characteristic.On Error: Error: Invalid payload in response:

**Comment by mbierman** [comment]
I'm getting similar things. 

	[6/18/2020, 11:51:03 AM] [Smart Life] [SET][Office switch] Characteristic.On Error: Error: Invalid payload in response: 
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:166:32
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:280:13
	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
	[6/18/2020, 11:51:06 AM] [Smart Life] [SET][Office switch] Characteristic.On Error: Error: Invalid payload in response: 
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:166:32
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:280:13
	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
	[6/18/2020, 11:51:23 AM] [Smart Life] [SET][Office switch] Characteristic.On Error: Error: Invalid payload in response: 
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:166:32
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:280:13
	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
	[6/18/2020, 11:51:25 AM] [Smart Life] [SET][Office switch] Characteristic.On Error: Error: Invalid payload in response: 
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:166:32
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:280:13
	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
	[6/18/2020, 11:51:27 AM] [Smart Life] [SET][Office switch] Characteristic.On Error: Error: Invalid payload in response: 
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:166:32
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:280:13
	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
	[6/18/2020, 11:51:28 AM] [Smart Life] [SET][Office switch] Characteristic.On Error: Error: Invalid payload in response: 
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:166:32
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:280:13
	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
	[6/18/2020, 11:51:31 AM] [Smart Life] [SET][Office switch] Characteristic.On Error: Error: Invalid payload in response: 
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:166:32
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:280:13
	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
	[6/18/2020, 11:51:35 AM] [Smart Life] [SET][Office switch] Characteristic.On Error: Error: Invalid payload in response: 
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:166:32
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:280:13
	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
	[6/18/2020, 11:52:08 AM] [Config] Changes to config.json saved.
	[6/18/2020, 11:52:15 AM] [Config] Changes to config.json saved.
	[6/18/2020, 11:52:20 AM] [Smart Life] [SET][Office switch] Characteristic.On Error: Error: Invalid payload in response: 
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:166:32
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:280:13
	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
	[6/18/2020, 11:52:21 AM] [Smart Life] [SET][Office switch] Characteristic.On Error: Error: Invalid payload in response: 
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:166:32
	    at /homebridge/node_modules/@milo526/homebridge-tuya-web/lib/tuyawebapi.js:280:13
	    at runMicrotasks (<anonymous>)
	    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by milo526** [comment]
Sorry for that, I was able to reproduce the error in 0.3.2 and I believe 03.3 fixed this.
Could you please confirm this @rcoletti116 and/or @mbierman

**Comment by mbierman** [comment]
/homebridge # npm install @milo526/homebridge-tuya-web@0.3.3
	+ @milo526/homebridge-tuya-web@0.3.3
	updated 1 package and audited 583 packages in 31.118s

	33 packages are looking for funding
	  run `npm fund` for details

	found 2 vulnerabilities (1 low, 1 moderate)
	  run `npm audit fix` to fix them, or `npm audit` for details
	/homebridge # npm audit
	npm ERR! code ELOCKVERIFY
	npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
	npm ERR!     Invalid: lock file's @milo526/homebridge-tuya-web@0.2.0 does not satisfy @milo526/homebridge-tuya-web@^0.3.3

	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2020-06-18T20_51_42_012Z-debug.log
	/homebridge # 

seems o.k. to me except for the installation errors I get.
