### ISSUE TITLE
The requested platform 'TuyaWebPlatform' has been registered multiple times

### ISSUE THREAD

**Issue by ahmadnazirafiq** [milo526/homebridge-tuya-web#147]
Was trying to add Smart Life logins for the first time with a second homebridge instance and got this error:

[29/12/2020, 19:54:58] Error: The requested platform 'TuyaWebPlatform' has been registered multiple times. Please be more specific by writing one of: homebridge-tuya-web.TuyaWebPlatform, @milo526/homebridge-tuya-web.TuyaWebPlatform
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:227:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:385:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)

Works for other Tuya plugins but most of them are outdated and unverified. Please help!

**Comment by milo526** [comment]
You have both the `homebridge-tuya-web` as well as `@milo526/homebridge-tuya-web` installed. The former of which is deprecated and should not longer be used. Please remove the `homebridge-tuya-web` plugin.

**Comment by ahmadnazirafiq** [comment]
Alright, it has been removed and fixed. However, if I physically press the switch manually it doesn’t reflect the actual power state on the Home app. Is that expected?

**Comment by milo526** [comment]
Yes that is expected; the API that this plugin uses is severely limited; it will take upwards of 5 minutes to update. Eventually it should reflect the correct state.

Sadly this is a limitation from Tuya, there is nothing I can do to change that.

**Comment by ahmadnazirafiq** [comment]
No worries. Keep up the good work 😉
