### ISSUE TITLE
Updated today 

### ISSUE THREAD

**Issue by jsrichie** [milo526/homebridge-tuya-web#19]
And all my devices are now offline error is now:

[6/19/2020, 1:43:29 PM] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/homebridge/node_modules/@milo526/homebridge-tuya-web/lib/light_accessory.js:227:39)
    at LightAccessory.updateAccessory (/homebridge/node_modules/@milo526/homebridge-tuya-web/lib/base_accessory.js:103:14)
    at /homebridge/node_modules/@milo526/homebridge-tuya-web/index.js:96:52
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by milo526** [comment]
I just pushed a pre-release to npm, you can reach that by installing `npm install @milo526/homebridge-tuya-web@next` would you be willing to install that and see if that solves your problem?

**Comment by milo526** [comment]
Closing due to lack of response on an issue that is supposedly fixed.
