### ISSUE TITLE
The switches don't update and receive error status 

### ISSUE THREAD

**Issue by atxmayur** [milo526/homebridge-tuya-web#25]
so the lamps and LED strips don't update when on but all the switches do. the error code is displayed below very often
[Smartlife] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/lib/light_accessory.js:227:39)
    at LightAccessory.updateAccessory (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/lib/base_accessory.js:103:14)
    at /usr/local/lib/node_modules/@milo526/homebridge-tuya-web/index.js:96:52
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by milo526** [comment]
When you created this issue you should have come across a page where you could select that you wanted to create a bug report. Using that format would have helped me a lot since I would have all and if not way more of the information that I need to solve this issue.
This issue might be solved in the pre-release v0.3.4-0. If it is not solved there please open a new issue following the bug report template.
Lastly a very similar issue was reported just 2 hours before yours (#24) showing a very similar issue. please search for existing issues before opening new once.
