### ISSUE TITLE
[NEW DEVICE] LED Strip Light

### ISSUE THREAD

**Issue by idjul** [milo526/homebridge-tuya-web#29]
Hi,

Thanks for adding this new device:

Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {   'devices': [   {   'data': {   'color_mode': 'scene',
                                                  'online': True,
                                                  'state': 'true'},
                                      'dev_type': 'light',
                                      'ha_type': 'light',
                                      'icon': 'https://images.tuyaeu.com/smart/icon/001460162698766TR4v1/1560138286cb1b0e7b07b.png',
                                      'id': 'bf88b214053bd9f37ep64n',
                                      'name': 'LED Strip Light'}],
                   'scenes': []}}

Error in Homebridge:

[7/7/2020, 20:39:44] [TuyaWebPlatform] Error retrieving devices states TypeError: Cannot read property 'brightness' of undefined
    at LightAccessory.updateState (/usr/lib/node_modules/homebridge-tuya-web/lib/light_accessory.js:222:43)
    at LightAccessory.updateAccessory (/usr/lib/node_modules/homebridge-tuya-web/lib/base_accessory.js:103:14)
    at /usr/lib/node_modules/homebridge-tuya-web/index.js:96:52
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by milo526** [comment]
This is 1) not a request to add a new device and 2) the bug is tracked in #28

**Comment by idjul** [comment]
Also, i can't change the color via homebridge, is it liked?
