### ISSUE TITLE
[NEW DEVICE] MOES - Smart Dimmer Switch

### ISSUE THREAD

**Issue by vleeuwenmenno** [milo526/homebridge-tuya-web#364]
**Device type**

MOES - Smart Dimmer Switch

**Device information**
The product: - MOES - Smart Dimmer Switch
It's a touch or rotary based dimmer to connect led, inc or CFL dimmable lights to.

At the moment it is being detected as a switch only I wasn't sure to post this as a bug or as a new device request.
When I change the device to be a dimmer it doesn't work properly anymore and with debug mode I get the following output on my console.

```
[11/20/2021, 1:11:06 AM] [TuyaWebPlatform] [Smart Dimmer Switch] - Unsetting debouncedDeviceStateRequestPromise
[11/20/2021, 1:11:06 AM] [TuyaWebPlatform] [Smart Dimmer Switch] - Resolving resolveDeviceStateRequest from cache
[11/20/2021, 1:11:06 AM] [TuyaWebPlatform] [Smart Dimmer Switch] Characteristic.On - [GET] true
[11/20/2021, 1:11:06 AM] [TuyaWebPlatform] [Smart Dimmer Switch] Characteristic.Brightness - [GET] 1
[11/20/2021, 1:11:06 AM] [TuyaWebPlatform] [Smart Dimmer Switch] Characteristic.Brightness - Tried to set brightness but failed to parse data. 
 { online: true, state: true, brightness: 1 }
[11/20/2021, 1:11:06 AM] [TuyaWebPlatform] [Smart Dimmer Switch] Characteristic.On - [GET] true
[11/20/2021, 1:11:06 AM] [TuyaWebPlatform] [Smart Dimmer Switch] Characteristic.Brightness - [GET] 1
[11/20/2021, 1:11:06 AM] [TuyaWebPlatform] [Smart Dimmer Switch] Characteristic.Brightness - Tried to set brightness but failed to parse data. 
 { online: true, state: true, brightness: 1 }
[11/20/2021, 1:11:06 AM] [TuyaWebPlatform] [Smart Dimmer Switch] Characteristic.On - [GET] true
[11/20/2021, 1:11:06 AM] [TuyaWebPlatform] [Smart Dimmer Switch] Characteristic.Brightness - [GET] 1
[11/20/2021, 1:11:06 AM] [TuyaWebPlatform] [Smart Dimmer Switch] Characteristic.Brightness - Tried to set brightness but failed to parse data. 
 { online: true, state: true, brightness: 1 }
```

Also changing the brightness to anything above the 1% throws an exception, it somehow seems like the device is using way higher numbers or something?

```
[11/20/2021, 1:17:22 AM] [TuyaWebPlatform] [Kitchen] Characteristic.Brightness - [GET] 1000
[11/20/2021, 1:17:22 AM] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 392 exceeded maximum of 100. See https://git.io/JtMGR for more info.
[11/20/2021, 1:17:22 AM] [@milo526/homebridge-tuya-web] Error: 
    at Brightness.Characteristic.characteristicWarning (/Users/menno/.nvm/versions/node/v16.13.0/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at Brightness.Characteristic.validateUserInput (/Users/menno/.nvm/versions/node/v16.13.0/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1986:16)
    at /Users/menno/.nvm/versions/node/v16.13.0/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1569:24
    at /Users/menno/.nvm/versions/node/v16.13.0/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at BrightnessCharacteristic.updateValue (/Users/menno/.nvm/versions/node/v16.13.0/lib/node_modules/@milo526/homebridge-tuya-web/src/accessories/characteristics/brightness.ts:75:19)
    at /Users/menno/.nvm/versions/node/v16.13.0/lib/node_modules/@milo526/homebridge-tuya-web/src/accessories/characteristics/brightness.ts:34:14
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I hope I supplied enough data, else please just poke me and I will gather some more details. I am a software engineer myself but I am not familiar with the codebase so feel free to point me in the right direction. 

EDIT: 

Python script output shows the following data for the device:
```
{   
    'data': {'online': True, 'state': True},
    'dev_type': 'switch',
    'ha_type': 'switch',
    'icon': 'https://images.tuyaeu.com/smart/icon/bay1603253771121HO88/16173513268eab6c7597c.png',
    'id': 'bf61a9b8e2aa6a3775qojq',
    'name': 'Smart Dimmer Switch'
}
```

**Comment by milo526** [comment]
What does your plugin configuration look like now?

**Comment by vleeuwenmenno** [comment]
Do you mean the entire JSON for the plugin?

**Comment by milo526** [comment]
The Tuya servers are exposing this devices as a switch and are erroring when setting its brightness.
Sadly it seems like this plugin will only allow you to set the state, not the brightness and it seems like I cannot change that due to limitations imposed by Tuya.
You could try and see if tuya's first-party plugin works better for you.
https://github.com/tuya/tuya-homebridge

**Comment by vleeuwenmenno** [comment]
Yeah I also realised this when attempting to call the tuya api by myself with some simple C# code
