### ISSUE TITLE
Error: Requesting too quickly.

### ISSUE THREAD

**Issue by rmit-s3686930-keyu** [milo526/homebridge-tuya-web#42]
**Describe the bug**
Homebridge log is giving `Error: Requesting too quickly.` errors frequently

**To Reproduce**
1. Kill Home app
2. Start Home app
3. Homebridge log gives 
```
Error: Requesting too quickly.
    at TuyaWebApi.discoverDevices (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/src/TuyaWebApi.ts:159:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Expected behavior**

**Screenshots**

**Device**
 - Plugin: @milo526/homebridge-tuya-web
 - Version: [See firmware in your homekit device]
 - Model : 0.4.1

**Comment by milo526** [comment]
Please remove the ```pollingInterval``` key from your config file and try not to open your Home.app for about an hour. This should reduce the number of errors you get.

The rest of this is an issue with Tuya which I can do very little about, the current release version of the plugin suppresses these errors, they are still very much there though.

**Comment by rmit-s3686930-keyu** [comment]
i got these errors with the `pollingInterval`  disabled, 

looking from these debug logs, i think it is trying to make http requests everytime i open Home app.
Will enabling `pollingInterval` help, since it will read device status from cache instead of making http request everytime i open Home app?
```
[7/30/2020, 10:40:08 AM] [MiOutletPlatform] [MiOutletPlatform][DEBUG]MiPlugBase - Outlet - getPower: off
[7/30/2020, 10:40:08 AM] [MiOutletPlatform] [MiOutletPlatform][DEBUG]MiPlugBase - Outlet - getOutletInUse: off
[7/30/2020, 10:40:08 AM] [TuyaWebPlatform] Sending HTTP GET request to /homeassistant/skill.
[7/30/2020, 10:40:09 AM] [TuyaWebPlatform] Error: Requesting too quickly.
    at TuyaWebApi.discoverDevices (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/src/TuyaWebApi.ts:159:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[7/30/2020, 10:40:12 AM] [TuyaWebPlatform] Sending HTTP GET request to /homeassistant/skill.
[7/30/2020, 10:40:13 AM] [TuyaWebPlatform] Error: Requesting too quickly.
    at TuyaWebApi.discoverDevices (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/src/TuyaWebApi.ts:159:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by milo526** [comment]
While what you state was true some time ago, this is no longer the case now. The cache is hard-coded to be 15 seconds. I strongly suspect that the `pollingInterval` will only actively hurt this issue, not help it (since it will just ensure that there are more request being made).

**Comment by rmit-s3686930-keyu** [comment]
Thanks for making that clear!
