### ISSUE TITLE
Loaded 0 Cached Accessories - Help

### ISSUE THREAD

**Issue by brades1607** [milo526/homebridge-tuya-web#445]
Receiving the following:

[5/22/2022, 4:48:17 PM] [TuyaWebPlatform] Launched child bridge with PID 4972
[5/22/2022, 4:48:17 PM] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform'
[5/22/2022, 4:48:17 PM] [TuyaWebPlatform] Loaded @milo526/homebridge-tuya-web v1.1.2 child bridge successfully
[5/22/2022, 4:48:17 PM] Loaded 0 cached accessories from cachedAccessories.0ED8E33CF889.
[5/22/2022, 4:48:17 PM] Homebridge v1.4.1 (HAP v0.10.2) (TuyaWebPlatform) is running on port 49931.

Login is correct and all settings correct. Email has no . before the @.

There are two devices in my Smart Life app.

Something being overlooked by me? Help appreciated!

**Describe the bug**

[5/22/2022, 4:48:17 PM] [TuyaWebPlatform] Launched child bridge with PID 4972
[5/22/2022, 4:48:17 PM] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform'
[5/22/2022, 4:48:17 PM] [TuyaWebPlatform] Loaded @milo526/homebridge-tuya-web v1.1.2 child bridge successfully
[5/22/2022, 4:48:17 PM] Loaded 0 cached accessories from cachedAccessories.0ED8E33CF889.
[5/22/2022, 4:48:17 PM] Homebridge v1.4.1 (HAP v0.10.2) (TuyaWebPlatform) is running on port 49931.

**Steps To Reproduce**

**Plugin Version**
 
 
 **Homebridge Config**
 
 
 ```json

```
 
 **Device Config**
 
 
 **Additional Context**

**Comment by milo526** [comment]
Please post the result of [the steps under "How to check whether the api this library uses can control your device".](https://github.com/milo526/homebridge-tuya-web#how-to-check-whether-the-api-this-library-uses-can-control-your-device)

Without this it is hard for me to help you with regards to this specific issue.

**Comment by brades1607** [comment]
Getting credentials
Traceback (most recent call last):
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fde0d989bb0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='px1.tuyaau.com', port=443): Max retries exceeded with url: /homeassistant/auth.do (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fde0d989bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:
Getting credentials
Traceback (most recent call last):
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-pack
Getting credentials
Traceback (most recent call last):
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/nix/store/p21fdyxqb3yqflpim7g8s1mymgpnqiv7-python3-3.8.12/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f91999e8bb0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='px1.tuyaau.com', port=443): Max retries exceeded with url: /homeassistant/auth.do (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f91999e8bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 20, in <module>
    auth_response = requests.post(
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/runner/TurquoiseImpressiveCharacterencoding/venv/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='px1.tuyaau.com', port=443): Max retries exceeded with url: /homeassistant/auth.do (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f91999e8bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))


**Comment by milo526** [comment]
While this might be the output of the script at the given time, it's an error and thus not very useful in getting me the data.
Could you try again and get the data output instead of this error 😄

**Comment by brades1607** [comment]
Hey Milo... still new to this.

This what you are after?

Getting credentials
Got credentials
{   'access_token': 'EUheu1653199044910EWEKjNPNQKv7eqo',
    'expires_in': 864000,
    'refresh_token': 'EUheu1653199044910EWEKj0pYFKbHmSQ',
    'token_type': 'bearer'}
Getting devices
Got devices
{   'header': {'code': 'SUCCESS', 'payloadVersion': 1},
    'payload': {'devices': [], 'scenes': []}}
!!! NOW REMOVE THIS FILE, SO YOUR CREDENTIALS (username, password) WON'T LEAK !!!

**Comment by milo526** [comment]
Yeah that looks good.
In the latter part we see:

```json
{
   "header":{
      "code":"SUCCESS",
      "payloadVersion":1
   },
   "payload":{
      "devices":[],
      "scenes":[]
   }
}
```

The empty devices array in the payload tells us that Tuya does not expose any devices to the API that this plugin is using.
Sadly not all of their devices are supported in this API and you seem to have a few of them which aren't.
Since I do not work for Tuya, there is nothing I can do to help you here.
You might have better luck with the plugin that tuya themselves develops.
You can find their plugin at https://github.com/tuya/tuya-homebridge
