### ISSUE TITLE
'Color Temperature': characteristic was supplied illegal value

### ISSUE THREAD

**Issue by sparklesrainbow** [milo526/homebridge-tuya-web#491]
Getting this error during reboot and initialization. This hangs homebridge. These are Costco bought Feit lights. 

[07/11/2022, 21:55:03] [TuyaWebPlatform] [MBR1] Characteristic.ColorTemperature - Characteristic 'ColorTemperature' will receive value lower than allowed mired (-1901) since provided Tuya kelvin value (36294) exceeds configured maximum Tuya kelvin value (2000). Please update your configuration!
[07/11/2022, 21:55:03] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Color Temperature': characteristic was supplied illegal value: number -1901 exceeded minimum of 140. See https://homebridge.io/w/JtMGR for more info.
[07/11/2022, 21:55:03] [@milo526/homebridge-tuya-web] Error: 
    at ColorTemperature.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2138:105)
    at ColorTemperature.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2050:14)
    at ColorTemperature.Characteristic.updateValue (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1457:20)
    at LightAccessory.setCharacteristic (/var/lib/homebridge/node_modules/@milo526/homebridge-tuya-web/src/accessories/BaseAccessory.ts:272:55)
    at ColorTemperatureCharacteristic.updateValue (/var/lib/homebridge/node_modules/@milo526/homebridge-tuya-web/src/accessories/characteristics/colorTemperature.ts:116:22)
    at LightAccessory.updateState (/var/lib/homebridge/node_modules/@milo526/homebridge-tuya-web/src/accessories/BaseAccessory.ts:420:9)
    at LightAccessory.updateAccessory (/var/lib/homebridge/node_modules/@milo526/homebridge-tuya-web/src/accessories/BaseAccessory.ts:413:10)
    at TuyaWebPlatform.refreshDeviceStates (/var/lib/homebridge/node_modules/@milo526/homebridge-tuya-web/src/platform.ts:192:41)
    at TuyaWebPlatform.discoverDevices (/var/lib/homebridge/node_modules/@milo526/homebridge-tuya-web/src/platform.ts:314:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[07/11/2022, 21:55:03] [TuyaWebPlatform] [Color Lights] Characteristic.Brightness - Characteristic 'Brightness' will receive value higher than allowed (272.22222222222223) since provided Tuya value (255) exceeds configured maximum Tuya value (100). Please update your configuration!
[07/11/2022, 21:55:03] [@milo526/homebridge-tuya-web] This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 272 exceeded maximum of 100. See https://homebridge.io/w/JtMGR for more info.
[07/11/2022, 21:55:03] [@milo526/homebridge-tuya-web] Error: 
    at Brightness.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2138:105)
    at Brightness.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2054:14)
    at Brightness.Characteristic.updateValue (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1457:20)
    at LightAccessory.setCharacteristic (/var/lib/homebridge/node_modules/@milo526/homebridge-tuya-web/src/accessories/BaseAccessory.ts:272:55)
    at BrightnessCharacteristic.updateValue (/var/lib/homebridge/node_modules/@milo526/homebridge-tuya-web/src/accessories/characteristics/brightness.ts:112:22)
    at LightAccessory.updateState (/var/lib/homebridge/node_modules/@milo526/homebridge-tuya-web/src/accessories/BaseAccessory.ts:420:9)
    at LightAccessory.updateAccessory (/var/lib/homebridge/node_modules/@milo526/homebridge-tuya-web/src/accessories/BaseAccessory.ts:413:10)
    at TuyaWebPlatform.refreshDeviceStates (/var/lib/homebridge/node_modules/@milo526/homebridge-tuya-web/src/platform.ts:192:41)
    at TuyaWebPlatform.discoverDevices (/var/lib/homebridge/node_modules/@milo526/homebridge-tuya-web/src/platform.ts:314:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by milo526** [comment]
Please read the following wiki article to find out how to configure your devices to solve this problem.

https://github.com/milo526/homebridge-tuya-web/wiki/Something-will-receive-higher-or-lower-value-than-allowed
