### ISSUE TITLE
Uninstall Failed

### ISSUE THREAD

**Issue by MatGriffin** [milo526/homebridge-tuya-web#55]
Plug was throwing the error requesting too quickly and causing all homebridge devices to not respond in HK app. Removed config and other items respond. Now go to uninstall plugin and this error:

```
SER: pi
DIR: /usr/local/lib
CMD: sudo -E -n npm uninstall @milo526/homebridge-tuya-web

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'wide-align'
Require stack:
- /usr/local/lib/node_modules/npm/node_modules/gauge/render-template.js
- /usr/local/lib/node_modules/npm/node_modules/gauge/plumbing.js
- /usr/local/lib/node_modules/npm/node_modules/gauge/index.js
- /usr/local/lib/node_modules/npm/node_modules/npmlog/log.js
- /usr/local/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/gauge/render-template.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/npm/node_modules/gauge/render-template.js',
    '/usr/local/lib/node_modules/npm/node_modules/gauge/plumbing.js',
    '/usr/local/lib/node_modules/npm/node_modules/gauge/index.js',
    '/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js',
    '/usr/local/lib/node_modules/npm/bin/npm-cli.js'
  ]
}

Command failed. Please review log for details.

```

**Comment by MatGriffin** [comment]
this is unrelated to this plug-in
