### ISSUE TITLE
Accessories no longer responding

### ISSUE THREAD

**Issue by gavinhuet** [milo526/homebridge-tuya-web#629]
Unable to control any of accessory via Homebridge or HomeKit.
Confirmed that everything is still working via the Tuya Smart app on iOS.

If I uninstall the plugin and re-install it, no accessories are found.

Issue arose over the weekend of 14-15 Dec 2024.

{
    "name": "TuyaWebPlatform",
    "options": {
        "username": "REDACTED",
        "password": "REDACTED",
        "countryCode": "64",
        "platform": "tuya"
    },
    "defaults": [
        {
            "id": "eb74d290572afee1261ez0",
            "device_type": "light",
            "min_brightness": "0",
            "max_brightness": "1100",
            "light_characteristics": [
                "Brightness"
            ]
        }
    ],
    "scenes": false,
    "_bridge": {
        "username": "0E:D4:55:BB:7C:7B",
        "port": 55921
    },
    "platform": "TuyaWebPlatform"
}

**Comment by mbdmbd** [comment]
Also seeing this. Have done a number of attempts at reconfiguring, removing cached accessoties, and no luck.  If I had to guess, I'd suspect that Tuya might have changed something at their side?

Running in a Docker container - current homebridge/homebridge:ubuntu

TuyaWebPlatform v1.1.5
Node v22.12.0
HomeBridge v1.8.5
HomeBridge UI v4.65.1

```
$ docker logs homebridge | grep -i tuya
...
[12/16/2024, 7:53:09 PM] Loaded plugin: @milo526/homebridge-tuya-web@1.1.5
[12/16/2024, 7:53:09 PM] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform'
[12/16/2024, 7:53:09 PM] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[12/16/2024, 7:53:09 PM] [TuyaWebPlatform] Initializing child bridge 0E:31:XX:XX:XX:XX
[12/16/2024, 7:53:10 PM] [TuyaWebPlatform] Launched child bridge with PID 152
[12/16/2024, 7:53:10 PM] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform'
[12/16/2024, 7:53:10 PM] [TuyaWebPlatform] Loaded @milo526/homebridge-tuya-web v1.1.5 child bridge successfully
[12/16/2024, 7:53:10 PM] Homebridge v1.8.5 (HAP v0.12.3) (TuyaWebPlatform) is running on port 32969.
[12/16/2024, 7:53:10 PM] [TuyaWebPlatform]
```

**Comment by bmdzi1** [comment]
Confirm same problem here. Also arose on the weekend of 14-15 December 2025. Have also tried deleting cached accessories.

Homebridge log shows the following:

16/12/2024, 22:48:09] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[16/12/2024, 22:48:09] Loading 1 accessories...
[16/12/2024, 22:48:13] [TuyaWebPlatform] 

The final entry above usually would state the login details and something like "successful connected" or similar.

**Comment by ckangnz** [comment]
I'm having the same issue. It was working perfectly fine and all of a sudden it's not working from today. I've only made a change to 'show scene' and all of my devices aren't updating either on hoobs nor homekit. It works on the Smartlife App, as well as Tuya Developer API calls. Seems hoobs API call isn't triggering the API correctly? I can't seem to turn on the debugger mode on Hoobs unfortunately :(

**Comment by brian-su** [comment]
I've had the same issue. But pure dumb luck I accidentally re-installed the plugin and set it up as a child bridge. Then adding the bridge to HomeKit has miraculously fixed everything. But I have 0 idea how or why.

**Comment by mbdmbd** [comment]
Have tried removing the child bridge, uninstalling plugin, re-installing, and still seeing the same issue.

```
[1/1/2025, 4:36:26 PM] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform'
[1/1/2025, 4:36:26 PM] [TuyaWebPlatform] Loaded @milo526/homebridge-tuya-web v1.1.5 child bridge successfully
[1/1/2025, 4:36:26 PM] Loaded 0 cached accessories from cachedAccessories.xxxxxxxxxxxx.
[1/1/2025, 4:36:26 PM] Homebridge v1.8.5 (HAP v0.12.3) (TuyaWebPlatform) is running on port 35632.
[1/1/2025, 4:36:27 PM] [TuyaWebPlatform] 
```

**Comment by raccoon-mh** [comment]
I'm having the same problem. The following methods didn't help.

- I tried reinstalling the new home bridge.
- I have reinstalled and updated this new plug-in.
- I tried changing my tuya smart life account.
- I tried to provide Virtual ID to connect directly.

I'm waiting for it to be resolved as soon as possible, and I'm willing to help you if you need help.

**Comment by Hellangel1987** [comment]
Same Issue Here - 

[01/01/2025, 15:45:40] [TuyaWebPlatform] Launched child bridge with PID 4695
[01/01/2025, 15:45:40] [TuyaWebPlatform] Loaded @milo526/homebridge-tuya-web v1.1.5 child bridge successfully
[01/01/2025, 15:45:40] Loaded 0 cached accessories from cachedAccessories.xxxxxxxxxxxxxxx.
[01/01/2025, 15:45:40] Homebridge v1.8.5 (HAP v0.12.3) (TuyaWebPlatform) is running on port 55536.
[01/01/2025, 15:45:40] 
[01/01/2025, 15:45:41] [TuyaWebPlatform] Missing required `id` property on device configuration, received:
{
  "device_type": "form"
}
[01/01/2025, 15:45:41] [TuyaWebPlatform] Enable cloud polling with interval 1200s

I'm waiting for it to be resolved as soon as possible, and I'm willing to help you if you need help.

**Comment by ckangnz** [comment]
I ended up moving away to tuya platform plugin..:( i liked this plugin more but it seems it's not maintained anymore..

**Comment by gavinhuet** [comment]
Likewise, it was the opportunity for me to move away from homebridge and tuya.

**Comment by 0chil** [comment]
Finally got it working. 
I got hint from what benreimers said and after some researching, I found [this](https://github.com/0x5e/homebridge-tuya-platform/issues/508).
The discussion is from similar plugin - having same issues.
Somehow disabling IPv6 system-wide makes SSL problems gone - maybe it's an issue related to IPv6 with Tuya IoT servers in some regions.

you should try following commands:
```bash
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
sudo sysctl -p
```

**Comment by bmdzi1** [comment]
Thank you so much Ochil!

I went into terminal on my home bridge, and copy pasted the commands above and all is now working again!

**Comment by alphaorderly** [comment]
Anyone has a same problem but not working with 0chil's guild

Enter

```
echo -e "\n# Disable IPv6" | sudo tee -a /etc/sysctl.conf
echo "net.ipv6.conf.all.disable_ipv6 = 1" | sudo tee -a /etc/sysctl.conf
echo "net.ipv6.conf.default.disable_ipv6 = 1" | sudo tee -a /etc/sysctl.conf

# Apply the changes immediately
sudo sysctl -p

echo "✅ IPv6 has been permanently disabled."
```

Just copy&paste this code on your server

NOW YOU KNOW

**Comment by baryah** [comment]
'[TuyaWebPlatform] Requesting new token
[1/3/2025, 10:36:57 pm] [TuyaWebPlatform] Sending HTTP GET request to /homeassistant/skill - Header: {"name":"Discovery","namespace":"discovery","payloadVersion":1}.
[1/3/2025, 10:36:58 pm] [TuyaWebPlatform] 
[1/3/2025, 10:36:58 pm] [TuyaWebPlatform] AggregateError: 
    at Function.AxiosError.from (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/node_modules/axios/lib/core/AxiosError.js:92:14)
    at RedirectableRequest.handleRequestError (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/node_modules/axios/lib/adapters/http.js:620:25)
    at RedirectableRequest.emit (node:events:518:28)
    at ClientRequest.eventHandlers.<computed> (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/node_modules/follow-redirects/index.js:49:24)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:104:11)
    at TLSSocket.socketErrorListener (node:_http_client:518:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at Axios.request (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/node_modules/axios/lib/core/Axios.js:45:41)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at TuyaWebApi.sendRequest (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/src/api/service.ts:264:22)
    at TuyaWebApi.discoverDevices (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/src/api/service.ts:45:22)
    at TuyaWebPlatform.discoverDevices (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/src/platform.ts:287:20)
    at TuyaWebPlatform.postLaunchSetup (/usr/local/lib/node_modules/@milo526/homebridge-tuya-web/src/platform.ts:121:7)'


was working fine - now the log says as above

**Comment by alphaorderly** [comment]
Anyone has problem even after changing value
add
ipv6.disable=1
on cmdline
